// Code generated by andurel v1.0.0-rc.2; DO NOT EDIT.
package validation

import (
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

func (b *ValidationBuilder) Required(field string, value any, message ...string) {
	if isMissing(value) {
		b.AddField(field, "required", messageOrDefault("is required", message))
	}
}

func (b *ValidationBuilder) RequiredWhen(condition bool, field string, value any, message ...string) {
	if condition {
		b.Required(field, value, message...)
	}
}

func (b *ValidationBuilder) MinLen(field string, value any, min int, message ...string) {
	str, present, ok := stringValue(value)
	if !ok || !present {
		return
	}

	if utf8.RuneCountInString(str) < min {
		b.AddFieldWithParams(
			field,
			"min",
			messageOrDefault(fmt.Sprintf("must be at least %d characters", min), message),
			map[string]any{"min": min},
		)
	}
}

func (b *ValidationBuilder) MaxLen(field string, value any, max int, message ...string) {
	str, present, ok := stringValue(value)
	if !ok || !present {
		return
	}

	if utf8.RuneCountInString(str) > max {
		b.AddFieldWithParams(
			field,
			"max",
			messageOrDefault(fmt.Sprintf("must be at most %d characters", max), message),
			map[string]any{"max": max},
		)
	}
}

func (b *ValidationBuilder) LenBetween(field string, value any, min int, max int, message ...string) {
	b.MinLen(field, value, min, message...)
	b.MaxLen(field, value, max, message...)
}

func (b *ValidationBuilder) OneOf(field string, value any, allowed ...string) {
	b.oneOf(field, value, "has an invalid value", allowed...)
}

func (b *ValidationBuilder) OneOfWithMessage(
	field string,
	value any,
	message string,
	allowed ...string,
) {
	b.oneOf(field, value, messageOrDefault("has an invalid value", []string{message}), allowed...)
}

func (b *ValidationBuilder) oneOf(field string, value any, message string, allowed ...string) {
	str, present, ok := stringValue(value)
	if !ok || !present {
		return
	}

	if slices.Contains(allowed, str) {
		return
	}

	b.AddFieldWithParams(
		field,
		"one_of",
		message,
		map[string]any{"allowed": allowed},
	)
}

func (b *ValidationBuilder) URL(field string, value any, message ...string) {
	str, present, ok := stringValue(value)
	if !ok || !present || strings.TrimSpace(str) == "" {
		return
	}

	if !isHTTPURL(str) {
		b.AddField(field, "url", messageOrDefault("must be a valid URL", message))
	}
}

func (b *ValidationBuilder) RequiredURL(field string, value any, message ...string) {
	b.Required(field, value, message...)
	b.URL(field, value, message...)
}

func (b *ValidationBuilder) MinItems(field string, value any, min int, message ...string) {
	length, ok := sliceLen(value)
	if !ok {
		return
	}

	if length < min {
		b.AddFieldWithParams(
			field,
			"min_items",
			messageOrDefault(fmt.Sprintf("must contain at least %d item(s)", min), message),
			map[string]any{"min": min},
		)
	}
}

func (b *ValidationBuilder) MaxItems(field string, value any, max int, message ...string) {
	length, ok := sliceLen(value)
	if !ok {
		return
	}

	if length > max {
		b.AddFieldWithParams(
			field,
			"max_items",
			messageOrDefault(fmt.Sprintf("must contain at most %d item(s)", max), message),
			map[string]any{"max": max},
		)
	}
}

func (b *ValidationBuilder) NoBlankItems(field string, value any, message ...string) {
	slice, ok := dereferencedValue(value)
	if !ok {
		return
	}
	if slice.Kind() != reflect.Slice && slice.Kind() != reflect.Array {
		return
	}

	for i := 0; i < slice.Len(); i++ {
		item := slice.Index(i)

		if item.Kind() == reflect.String && strings.TrimSpace(item.String()) == "" {
			b.Add(
				normalizeField(field)+"["+strconv.Itoa(i)+"]",
				"required",
				messageOrDefault("is required", message),
			)
		}
	}
}

func (b *ValidationBuilder) TimeBeforeOrEqual(
	startField string,
	startValue any,
	endField string,
	endValue any,
	message ...string,
) {
	start, startOK := timeValue(startValue)
	end, endOK := timeValue(endValue)

	if !startOK || !endOK {
		return
	}

	if start.After(end) {
		b.AddFieldWithParams(
			startField,
			"before_or_equal",
			messageOrDefault("must be before or equal to the end time", message),
			map[string]any{"other": normalizeField(endField)},
		)
	}
}

func (b *ValidationBuilder) True(field string, value any, message ...string) {
	boolValue, ok := requiredBool(value)
	if !ok || !boolValue {
		b.AddField(field, "true", messageOrDefault("must be true", message))
	}
}

func messageOrDefault(defaultMessage string, messages []string) string {
	if len(messages) == 0 || strings.TrimSpace(messages[0]) == "" {
		return defaultMessage
	}

	return messages[0]
}
