// Package inertia provides Inertia.js rendering helpers.
// Code generated by andurel v1.2.9; DO NOT EDIT.
package inertia

import (
	"encoding/json"
	"fmt"
	"html/template"
	"strings"

	"mortenvistisen/assets"
	"mortenvistisen/config"
	"mortenvistisen/internal/server"
	"mortenvistisen/router/routes"
)

type viteTags struct {
	ViteHead template.HTML
	ViteBody template.HTML
}

type viteManifestEntry struct {
	File    string   `json:"file"`
	CSS     []string `json:"css"`
	Src     string   `json:"src"`
	IsEntry bool     `json:"isEntry"`
}

func initVite() (*viteTags, error) {
	if config.Env != server.ProdEnvironment {
		tags := &viteTags{
			ViteHead: template.HTML(`<script type="module" src="http://localhost:5173/assets/dist/@vite/client"></script>`),
		}

		tags.ViteHead += template.HTML(`<script type="module">
import RefreshRuntime from "http://localhost:5173/assets/dist/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>`)
		tags.ViteBody = template.HTML(`<script type="module" src="http://localhost:5173/assets/dist/resources/js/app.tsx"></script>`)

		return tags, nil
	}

	data, err := assets.Files.ReadFile("dist/vite/manifest.json")
	if err != nil {
		return nil, fmt.Errorf("vite: read manifest: %w", err)
	}

	var manifest map[string]viteManifestEntry
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("vite: parse manifest: %w", err)
	}

	entry, ok := manifest["resources/js/app.tsx"]
	if !ok {
		return nil, fmt.Errorf("vite: entry point not found in manifest")
	}

	tags := &viteTags{}
	viteBuildPrefix := strings.TrimSuffix(routes.ViteBuild.Path(), "*")
	for _, css := range entry.CSS {
		tags.ViteHead += template.HTML(`<link rel="stylesheet" href="` + viteBuildPrefix + css + `">`)
	}
	tags.ViteBody = template.HTML(`<script type="module" src="` + viteBuildPrefix + entry.File + `"></script>`)

	return tags, nil
}
