// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCategorys = `-- name: CountCategorys :one
select count(*) from categories
`

// CountCategorys
//
//	select count(*) from categories
func (q *Queries) CountCategorys(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countCategorys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :exec
delete from categories where id=$1
`

// DeleteCategory
//
//	delete from categories where id=$1
func (q *Queries) DeleteCategory(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.Exec(ctx, deleteCategory, id)
	return err
}

const insertCategory = `-- name: InsertCategory :one
insert into
    categories (id, created_at, updated_at, name, slug, description, color)
values
    ($1, now(), now(), $2, $3, $4, $5)
returning id, created_at, updated_at, name, slug, description, color
`

type InsertCategoryParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description pgtype.Text
	Color       pgtype.Text
}

// InsertCategory
//
//	insert into
//	    categories (id, created_at, updated_at, name, slug, description, color)
//	values
//	    ($1, now(), now(), $2, $3, $4, $5)
//	returning id, created_at, updated_at, name, slug, description, color
func (q *Queries) InsertCategory(ctx context.Context, db DBTX, arg InsertCategoryParams) (Category, error) {
	row := db.QueryRow(ctx, insertCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
	)
	return i, err
}

const queryAllCategorys = `-- name: QueryAllCategorys :many
select id, created_at, updated_at, name, slug, description, color from categories
`

// QueryAllCategorys
//
//	select id, created_at, updated_at, name, slug, description, color from categories
func (q *Queries) QueryAllCategorys(ctx context.Context, db DBTX) ([]Category, error) {
	rows, err := db.Query(ctx, queryAllCategorys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryCategoryByID = `-- name: QueryCategoryByID :one
select id, created_at, updated_at, name, slug, description, color from categories where id=$1
`

// QueryCategoryByID
//
//	select id, created_at, updated_at, name, slug, description, color from categories where id=$1
func (q *Queries) QueryCategoryByID(ctx context.Context, db DBTX, id uuid.UUID) (Category, error) {
	row := db.QueryRow(ctx, queryCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
	)
	return i, err
}

const queryCategorys = `-- name: QueryCategorys :many
select id, created_at, updated_at, name, slug, description, color from categories
`

// QueryCategorys
//
//	select id, created_at, updated_at, name, slug, description, color from categories
func (q *Queries) QueryCategorys(ctx context.Context, db DBTX) ([]Category, error) {
	rows, err := db.Query(ctx, queryCategorys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryPaginatedCategorys = `-- name: QueryPaginatedCategorys :many
select id, created_at, updated_at, name, slug, description, color from categories 
order by created_at desc 
limit $2::bigint offset $1::bigint
`

type QueryPaginatedCategorysParams struct {
	Offset int64
	Limit  int64
}

// QueryPaginatedCategorys
//
//	select id, created_at, updated_at, name, slug, description, color from categories
//	order by created_at desc
//	limit $2::bigint offset $1::bigint
func (q *Queries) QueryPaginatedCategorys(ctx context.Context, db DBTX, arg QueryPaginatedCategorysParams) ([]Category, error) {
	rows, err := db.Query(ctx, queryPaginatedCategorys, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
update categories
    set updated_at=now(), name=$2, slug=$3, description=$4, color=$5
where id = $1
returning id, created_at, updated_at, name, slug, description, color
`

type UpdateCategoryParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description pgtype.Text
	Color       pgtype.Text
}

// UpdateCategory
//
//	update categories
//	    set updated_at=now(), name=$2, slug=$3, description=$4, color=$5
//	where id = $1
//	returning id, created_at, updated_at, name, slug, description, color
func (q *Queries) UpdateCategory(ctx context.Context, db DBTX, arg UpdateCategoryParams) (Category, error) {
	row := db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
	)
	return i, err
}

const upsertCategory = `-- name: UpsertCategory :one
insert into
    categories (id, created_at, updated_at, name, slug, description, color)
values
    ($1, now(), now(), $2, $3, $4, $5)
on conflict (id) do update set updated_at=now(), name=excluded.name, slug=excluded.slug, description=excluded.description, color=excluded.color
returning id, created_at, updated_at, name, slug, description, color
`

type UpsertCategoryParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description pgtype.Text
	Color       pgtype.Text
}

// UpsertCategory
//
//	insert into
//	    categories (id, created_at, updated_at, name, slug, description, color)
//	values
//	    ($1, now(), now(), $2, $3, $4, $5)
//	on conflict (id) do update set updated_at=now(), name=excluded.name, slug=excluded.slug, description=excluded.description, color=excluded.color
//	returning id, created_at, updated_at, name, slug, description, color
func (q *Queries) UpsertCategory(ctx context.Context, db DBTX, arg UpsertCategoryParams) (Category, error) {
	row := db.QueryRow(ctx, upsertCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
	)
	return i, err
}
